export const OPEN_TRUMPIA_ACCOUNT_REGISTER_MODAL = 'OPEN_TRUMPIA_ACCOUNT_REGISTER_MODAL';
export const TRUMPIA_ACCOUNT_REGISTER_MODAL_ID = 'nTAM';

export const REGISTER_REQUESTING = 'REGISTER_REQUESTING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
